[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
competition_constructor_program = "63yvyYYUHSZyHEKnz4YerXBvZ5VomBwZtLF1XLmSWfbR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = """yarn run ts-mocha -p ./tsconfig.json -t 1000000 \
./tests/program_config.ts                                 \
./tests/constructor.ts                                    \
./tests/swiss-system/swiss_system.ts                      \
./tests/swiss-system/vault_create.ts                      \
./tests/swiss-system/vault_spl_create.ts                  \
./tests/swiss-system/leaderboard_create.ts                \
./tests/swiss-system/participant_create.ts                \
./tests/swiss-system/points_award.ts                      \
./tests/swiss-system/winner_determine.ts                  \
./tests/swiss-system/prize_withdraw.ts                    \
"""
